### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by MigAP** [gramian/matrico#1]
Hello, 

There seems to be an  error in the  [wiki](doc/matrico.wiki) regarding the number or arguments in the functions `mx-ode2-hyp` and `mx-ode2-ssp`: 

https://github.com/gramian/matrico/blob/04ca69c08dcc8349daa70452c2c5a587027d82f5/doc/matrico.wiki?plain=1#L503

In the  [heat](demos/heat.scm) demo, only 4 arguments are passed to the function: 

https://github.com/gramian/matrico/blob/04ca69c08dcc8349daa70452c2c5a587027d82f5/demos/heat.scm#L27

Cheers, 
Miguel

**Comment by gramian** [comment]
Hi,
thanks for reporting this. I fixed it already in the online wiki http://wiki.call-cc.org/eggref/5/matrico#analysis . All files in this repo will be updated as soon as version 0.6 is released (soon).
